In [1]:
leap_year = lambda year : (year % 4 == 0 and year % 100 != 0 )or (year % 400 == 0 )
year = 2024 
print(leap_year(year))

True


In [2]:

# data 
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [3]:
import pandas as pd 
renuable_resources=["Solar","Wind","Hydropower","Geothermal","Biomass" ]


In [4]:
renuable_series=pd.Series(renuable_resources)
print("Renewable Resources : ")
print(renuable_series)

Renewable Resources : 
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [5]:
projects_df=pd.DataFrame(data)
projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [7]:
projects_df.shape

(5, 6)

In [26]:
projects_df[2:4]

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
2  Hydropower Y  Hydropower            200               350  Washington   
3  Solar Roof Z       Solar             50               100      Nevada   

   Completion Year  
2             2022  
3             2025

In [32]:
projects_df.iloc[[1,2]]

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022

In [33]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes


In [36]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [41]:
mean1=projects_df["Capacity (MW)"].mean()
print(mean1)

160.0


In [54]:
sum1=0
sum2=0
for i in projects_df["Capacity (MW)"]:
    print(i)
    sum2=sum2+i
    sum1=sum1 + ((mean1 - i )**2)
# print(len(projects_df["Capacity (MW)"]))
var=sum1/len(projects_df["Capacity (MW)"])
print(var)
print(sum2)

150
300
200
50
100
5
7400.0
800


In [44]:
import math

In [46]:
print(math.sqrt(var))

86.02325267042627


In [63]:
high_capacity_projects=projects_df[projects_df["Capacity (MW)"]>100]
# print(high_capacity_projects)
high_capacity_projects.head()
# print(type(high_capacity_projects))

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [64]:
projects_df["Cost_per_MW"]=projects_df["Cost (Million $)"]/projects_df["Capacity (MW)"]

In [65]:
projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost_per_MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000

In [66]:
# Aggregation 
total_capacity=projects_df["Capacity (MW)"].sum()
total_cost=projects_df["Cost (Million $)"].sum()
print(f"total capacity {total_capacity}")
print(f"total cost {total_cost}")

total capacity 800
total cost 1300


In [67]:
grouped_data=projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("Total capacity by Technology : ")
print(grouped_data)

Total capacity by Technology : 
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [69]:
grouped_data_cost=projects_df.groupby("Technology")["Cost (Million $)"].sum()
print("Total cost by Technology : ")
print(grouped_data_cost)

Total cost by Technology : 
Technology
Geothermal    250
Hydropower    350
Solar         300
Wind          400
Name: Cost (Million $), dtype: int64


In [73]:
import numpy as np 
array=np.array([1,2,3])
print(array)

[1 2 3]


In [86]:
_2darray=np.array([
    
        [[1,2,3],[3,4,3]],
        [[1,2,3],[3,4,3]]
    ])
print(_2darray)

[[[1 2 3]
  [3 4 3]]

 [[1 2 3]
  [3 4 3]]]


In [83]:
print(_2darray.shape)
print(_2darray.size)
print(_2darray.dtype)
print(_2darray.itemsize)
print(_2darray.ndim)

(2, 2, 3)
12
int32
4
3


In [96]:
x=np.ones(3)
y=np.zeros(3)
z=np.random.random(_2darray.shape)
print(x,y,z)

[1. 1. 1.] [0. 0. 0.] [[[0.00328994 0.22306417 0.70711739]
  [0.84745532 0.87973983 0.51780535]]

 [[0.74120485 0.19005928 0.06984669]
  [0.7208644  0.58603977 0.55772425]]]


In [103]:
array1=np.full((3,3),1)
print(array1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [105]:
array2=np.identity(3)
print(array2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [108]:
arange_fun=np.arange(0,10,2)
print(arange_fun)

[0 2 4 6 8]


In [115]:
linspace_matrix=np.linspace(5,10,3)
print(linspace_matrix)
print(linspace_matrix.size)

[ 5.   7.5 10. ]
3


In [119]:
data=np.array([1,2,3,4,5,6,7,9,10])
print(data,"sample array ")
print(data[:])
print(data[::1])
print(data[::2])
print(data[::-1])

[ 1  2  3  4  5  6  7  9 10] sample array 
[ 1  2  3  4  5  6  7  9 10]
[ 1  2  3  4  5  6  7  9 10]
[ 1  3  5  7 10]
[10  9  7  6  5  4  3  2  1]


In [121]:
array_string=np.array([])
s=input()
def check_pal(string):
    for c in string:
        np.append(array_string, c)
    a=array_string
    b=array_string[::-1]
    if a==b: print("palindrome ") 
    else : print("not ")
check_pal(s)


not 


C:\Users\jadit\AppData\Local\Temp\ipykernel_25024\3348873089.py:8: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if a==b: print("palindrome ")


In [124]:
a_new_array=np.array([1,2,3,4,5,6,7,9,10])
# res_array=a_new_array.reshape(2,3)
res1_array=a_new_array.reshape(3,3)
# print(res_array)
print(res1_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  9 10]]


In [125]:
print(res1_array.T)

[[ 1  4  7]
 [ 2  5  9]
 [ 3  6 10]]


In [134]:
print(res1_array.flatten())
print(res1_array.flatten('F'))

[ 1  2  3  4  5  6  7  9 10]
[ 1  4  7  2  5  9  3  6 10]


In [135]:
# data manipulation 

data=np.array([1,2,3,4,5,6,7,9,10])

mean=np.mean(data)
median=np.median(data)
print(mean,median)

5.222222222222222 5.0


In [ ]:
energy_cons=np.array([1200,3400,2900,1800,2500])
print(energy_cons)
print("Energy consumption in MWH is ")
print()

In [136]:
# Create an array for energy consumption (in kWh)
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)

Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0
